language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
after_success: npm run coverage
env:
  global:
    - ACCESSTOKENSECRET="Your random key - its just string, you could even use this.1"
    - REFRESHTOKENSECRET="Your random key - its just string, you could even use this.2"
    - MFATOKENSECRET="Your random key - its just string, you could even use this.3"
    - PORT=4000
    - RANKCUTOFF=79
    - MFAWINDOW=2
    - MFASECRETLENGTH=20
